spring:
  application:
    name: DocumentRetrievalManagementSystem
  profiles:
    active: dev

server:
  port: 8070

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.project.documentretrievalmanagementsystem.mybatis.entity

##mybatis-plus配置控制台打印完整带参数SQL语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl