spring:
  redis:
    host: 43.140.197.50
    port: 6379
    password: Xjs02220012
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  elasticsearch:
    rest:
      # 是否启用es
      enable: true
      uris: 127.0.0.1:9200
      host: 127.0.0.1
      port: 9200
  datasource:
    url: jdbc:mysql://localhost:3306/document?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Xjs02220012

my:
  basePath: D:/code/source/material/
  UserPath: D:/code/source/user/
  basePathT: D:/code/source/txt/

  modelPath: D:/MHC/pycharm/pythonProject/cpt-base
  pythonPath: E:/develop/Anaconda/Anaconda3/envs/pytorch/python.exe
  scriptPath: D:/MHC/pycharm/pythonProject