spring:
  redis:
    host: 43.140.197.50
    port: 6379
    password: Xjs02220012
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  elasticsearch:
    rest:
      # 是否启用es
      enable: true
      uris: 43.140.197.50:9200
      host: 43.140.197.50
      port: 9200
  datasource:
    url: jdbc:mysql://43.140.197.50:3306/document?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Xjs02220012

my:
  basePath: /usr/local/java/JavaProject/DocumentRetrievalManagementSystem/material/
  basePathT: /usr/local/java/JavaProject/DocumentRetrievalManagementSystem/TXT/
  modelPath: D:/code/source/document_retrieval_management_system/cpt-version/cpt-base
  pythonPath: D:/anaconda/envs/document/python.exe
  scriptPath: D:/code/source/document_retrieval_management_system/cpt-version